import 'package:flutter/material.dart';

class AppLocalizations {
  AppLocalizations(this.locale);

  final Locale locale;

  static const LocalizationsDelegate<AppLocalizations> delegate = _AppLocalizationsDelegate();

  static AppLocalizations of(BuildContext context) {
    final AppLocalizations? localizations = Localizations.of<AppLocalizations>(context, AppLocalizations);
    return localizations ?? AppLocalizations(const Locale('en'));
  }

  static const Map<String, Map<String, String>> _values = <String, Map<String, String>>{
    'en': <String, String>{
      'common.continue': 'Continue',
      'common.retry': 'Retry',
      'common.finishSetup': 'Finish setup',
      'common.saving': 'Saving…',
      'common.done': 'Done',
      'common.cancel': 'Cancel',
      'common.back': 'Back',
      'common.requiredField': 'This field is required.',
      'language.badge': 'KSA-ready patient experience',
      'language.subtitle': 'Start your digital care journey with a calmer, more guided experience.',
      'language.chooseTitle': 'Choose your language',
      'language.chooseBody': 'Select the language for sign-in, onboarding, and your patient dashboard.',
      'language.englishSubtitle': 'Recommended for most seed content',
      'language.arabicSubtitle': 'Arabic-ready patient interface',
      'language.note': 'After sign-in you will complete profile setup and consent once before using booking and care features.',
      'signin.badge': 'Patient sign in',
      'signin.title': 'Welcome',
      'signin.subtitle': 'Enter your details and receive a one-time code to access appointments, messages, prescriptions, and records.',
      'signin.formTitle': 'Sign in or register',
      'signin.formBody': 'New patients are registered automatically. We will send a six-digit code to verify your email.',
      'signin.firstNameLabel': 'First name',
      'signin.lastNameLabel': 'Last name',
      'signin.identifierLabel': 'Email',
      'signin.seedTitle': 'Seeded test account',
      'signin.seedBody': 'OTP is delivered through the live API flow.',
      'signin.devPreview': 'Development OTP preview',
      'signin.submit': 'Send one-time code',
      'signin.submitting': 'Sending code…',
      'otp.title': 'One-time password',
      'otp.subtitle': 'Enter the six-digit verification code to continue securely into CarePoint.',
      'otp.codeLabel': 'Verification code',
      'otp.devCode': 'Development code',
      'otp.verify': 'Verify and continue',
      'otp.verifying': 'Verifying…',
      'otp.resend': 'Resend code',
      'otp.enterFullCode': 'Enter the full 6-digit verification code.',
      'otp.verifyCodeTitle': 'Verify code',
      'otp.verifyCodeSubtitle': 'We sent a six-digit code to {identifier}.',
      'otp.secureBadge': 'Secure sign in',
      'otp.almostThere': 'Almost there',
      'otp.heroBody': 'Enter the code to continue into your CarePoint experience.',
      'otp.timerWait': 'Request another code in 00:{seconds}',
      'otp.timerReady': 'You can request a new code now.',
      'otp.sending': 'Sending…',
      'profile.title': 'Profile setup',
      'profile.subtitle': 'Identity, safety, and care coordination details',
      'profile.heroBadge': 'Step 1 of 2',
      'profile.heroTitle': 'Complete your patient profile',
      'profile.heroBody': 'We use these details to personalize visits, match services, and support safe care delivery.',
      'profile.fullName': 'Full name',
      'profile.dateOfBirth': 'Date of birth',
      'profile.gender': 'Gender',
      'profile.genderFemale': 'Female',
      'profile.genderMale': 'Male',
      'profile.genderPreferNot': 'Prefer not to say',
      'profile.nationalId': 'National ID',
      'profile.emergencyContact': 'Emergency contact',
      'profile.nationality': 'Nationality',
      'profile.region': 'Country / region',
      'profile.regionSaudi': 'Saudi Arabia',
      'profile.regionGcc': 'GCC',
      'profile.regionOther': 'Other',
      'profile.requiredError': 'Please complete the required profile fields before continuing.',
      'consent.title': 'Consent Center',
      'consent.hero': 'Review your telehealth, data-sharing, and communication preferences before using digital services.',
      'consent.telehealthTitle': 'Telehealth consent',
      'consent.telehealthBody': 'Required for video visits and care-team communications tied to appointments.',
      'consent.dataTitle': 'Data-sharing consent',
      'consent.dataBody': 'Required to share records and history with the assigned care team inside CarePoint.',
      'consent.notificationsTitle': 'Notifications',
      'consent.notificationsBody': 'Optional reminders for appointments, messages, and medication updates.',
      'consent.note': 'Consent choices are now persisted through the API with audit timestamps and version-aware history so onboarding can resume safely across devices.',
      'consent.requiredError': 'Telehealth and data-sharing consent are required to continue in this starter flow.',
      'home.findProvider': 'Find provider',
      'home.viewAppointments': 'View appointments',
      'home.notifications': 'Notifications',
      'home.unread': 'unread',
      'home.highPriority': 'high priority',
      'home.refills': 'Refills',
      'home.active': 'active',
      'home.escalated': 'escalated',
      'home.governance': 'Governance',
      'home.open': 'open',
      'home.highPriorityReminders': 'high priority reminders',
      'home.wallet': 'Wallet',
      'home.methods': 'methods',
      'home.paymentsSavedMethods': 'Payments & saved methods',
      'home.quickActions': 'Quick actions',
      'home.bookCare': 'Book care',
      'home.messages': 'Messages',
      'home.labs': 'Labs',
      'home.records': 'Records',
      'home.latestUpdates': 'Latest updates',
      'home.noNotifications': 'No new notifications',
      'home.caughtUp': 'You are caught up for now.',
      'home.update': 'Update',
      'home.remindersAttention': 'Reminders requiring attention',
      'home.reminder': 'Reminder',
      'home.schedulePending': 'Schedule pending',
      'home.readyToBook': 'Ready to book your next visit?',
      'home.readyToBookBody': 'Find a provider, compare services, and complete your booking in a guided flow.',
      'home.welcomeBack': 'Welcome back',

      'home.family': 'Family',
      'home.profile': 'Profile',
      'home.activeProfile': 'Active profile',
      'entry.badge': 'Unified patient entry',
      'entry.title': 'Start in one guided screen',
      'entry.subtitle': 'Region, language, sign-in, and consent are combined before OTP verification.',
      'entry.heroBody': 'Choose your language, confirm the care region, enter your email or phone, and grant the required care consents before the one-time password step.',
      'entry.languageTitle': 'Language and region',
      'entry.english': 'English',
      'entry.arabic': 'Arabic',
      'entry.regionLabel': 'Region',
      'entry.regionSaudi': 'Saudi Arabia',
      'entry.regionGcc': 'GCC',
      'entry.regionOther': 'Other',
      'entry.identifierLabel': 'Email or mobile number',
      'entry.identifierHint': 'name@example.com or +9665…',
      'entry.consentTitle': 'Required care consents',
      'entry.consentBody': 'Telehealth and data-sharing consent are required so your care team can safely coordinate care and access your records when you book visits.',
      'entry.continueToOtp': 'Continue to OTP',
      'entry.requiredError': 'Enter your identifier and accept telehealth plus data-sharing consent before continuing.',
      'profile.familyProfileTitle': 'Family member profile',
      'profile.familyProfileSubtitle': 'Separate medical data for the selected dependent profile',
      'profile.familyBadge': 'Dependent context',
      'profile.familyHeroTitle': 'Manage this family member safely',
      'profile.familyHeroBody': 'Each family member keeps separate questionnaire answers, attached reports, and sharing controls.',
      'profile.questionnaireTitle': 'Health questionnaire',
      'profile.questionnaireBody': 'Capture the health history, risks, medications, and baseline facts needed for safe clinical review.',
      'profile.questionnaireProgress': 'Questionnaire progress',
      'profile.questionnaireVitalsTitle': 'Step 1: Vitals',
      'profile.questionnaireVitalsBody': 'Enter the baseline physical measurements before continuing to the rest of the questionnaire.',
      'profile.questionnaireHistoryTitle': 'Step 2: Medical history',
      'profile.questionnaireHistoryBody': 'Add allergies, conditions, medications, and surgeries in a simple guided section.',
      'profile.questionnaireSafetyTitle': 'Step 3: Lifestyle and safety',
      'profile.questionnaireSafetyBody': 'Complete the remaining health-risk and emergency details before saving the profile.',
      'profile.questionnaireNext': 'Next section',
      'profile.questionnaireReview': 'Review vitals',
      'profile.bloodType': 'Blood type',
      'profile.allergies': 'Allergies',
      'profile.conditions': 'Chronic conditions',
      'profile.currentMedications': 'Current medications',
      'profile.pastSurgeries': 'Past surgeries',
      'profile.heightCm': 'Height (cm)',
      'profile.weightKg': 'Weight (kg)',
      'profile.heightValidationError': 'Enter a valid height in centimeters or leave the field empty.',
      'profile.weightValidationError': 'Enter a valid weight in kilograms or leave the field empty.',
      'profile.questionnaireRecovered': 'Some saved questionnaire selections were not supported and were reset to safe defaults.',
      'profile.questionnaireLoadFallback': 'The questionnaire could not be loaded from the server. You can continue editing and try again.',
      'profile.questionnaireDedicatedSubtitle': 'Complete the questionnaire in a separate guided flow so each step loads safely and clearly.',
      'profile.questionnaireBadge': 'Guided flow',
      'profile.questionnaireCompletionLabel': 'Questionnaire completion',
      'profile.questionnaireOpen': 'Open questionnaire',
      'profile.questionnaireEdit': 'Edit questionnaire',
      'profile.questionnaireSaved': 'Questionnaire details were updated and are ready to save with the profile.',
      'profile.questionnaireDraftSaved': 'Section saved locally. Continue to the next step.',
      'profile.questionnaireDraftRestored': 'Your saved questionnaire draft was restored. Continue where you left off.',
      'profile.medicalDraftTitle': 'Unsaved medical profile draft',
      'profile.medicalDraftBody': 'You have unsaved questionnaire, report, or sharing changes on this profile. Resume them now or discard the local draft.',
      'profile.medicalDraftSaved': 'Medical profile changes were saved locally on this device.',
      'profile.medicalDraftRestored': 'Your unsaved medical profile draft was restored on this page.',
      'profile.medicalDraftResumed': 'Draft resumed. Review the questionnaire and reports before saving.',
      'profile.medicalDraftDiscarded': 'The local medical profile draft was discarded and the latest saved data was reloaded.',
      'profile.medicalDraftResume': 'Resume draft',
      'profile.medicalDraftDiscard': 'Discard draft',
      'profile.questionnaireCompleteAndReturn': 'Complete and return',
      'profile.questionnaireSummaryBody': 'Open the dedicated questionnaire page to complete or review the guided health questions.',
      'profile.questionnaireEmptyStateTitle': 'Questionnaire not started',
      'profile.questionnaireEmptyStateBody': 'Open the questionnaire to record vitals, medical history, and safety details before saving the profile.',
      'profile.questionnaireCompleted': 'Questionnaire complete',
      'profile.questionnaireIncomplete': 'Questionnaire incomplete',
      'profile.questionnaireVitalsRequired': 'Height and weight are required before continuing to the next questionnaire step.',
      'profile.smokingNever': 'Never',
      'profile.smokingFormer': 'Former',
      'profile.smokingCurrent': 'Current',
      'profile.pregnancyNotApplicable': 'Not applicable',
      'profile.pregnancyPregnant': 'Pregnant',
      'profile.pregnancyPlanning': 'Planning',
      'profile.preferNotToSay': 'Prefer not to say',
      'profile.smokingStatus': 'Smoking status',
      'profile.pregnancyStatus': 'Pregnancy status',
      'profile.emergencyNotes': 'Emergency notes',
      'profile.reportsTitle': 'Diagnostic history and reports',
      'profile.reportsBody': 'Attach report metadata and control which scheduled doctors can review it.',
      'profile.addReport': 'Add report',
      'profile.reportFileName': 'Report file name',
      'profile.reportCategory': 'Category',
      'profile.reportDate': 'Report date',
      'profile.providerName': 'Doctor / author name',
      'profile.facilityName': 'Facility',
      'profile.notes': 'Notes',
      'profile.shareWithDoctors': 'Share with scheduled doctors only',
      'profile.shareWithDoctorsBody': 'Reports remain private unless the patient explicitly allows access for doctors linked to scheduled appointments.',
      'profile.sharedDoctorList': 'Currently scheduled doctors',
      'profile.noReportsTitle': 'No reports attached yet',
      'profile.noReportsBody': 'Add diagnostic history, imaging results, discharge summaries, or lab reports here.',
      'profile.endOfPageTitle': 'No more information available',
      'profile.endOfPageBody': 'You have reached the end of the profile page. Pull down to refresh if you expected more details.',
      'family.title': 'Family profiles',
      'family.subtitle': 'Add dependents, switch profiles, and keep medical data isolated per patient.',
      'family.profileCount': 'profiles',
      'family.heroTitle': 'Manage care for the whole family',
      'family.heroBody': "Create separate family profiles, switch between them, and complete each person's medical data independently.",
      'family.addMember': 'Add family member',
      'family.memberName': 'Family member name',
      'family.relationship': 'Relationship',
      'family.currentContext': 'Current patient context',
      'family.selfProfile': 'My profile',
      'family.switchToSelf': 'Switch back to my profile',
      'family.defaultAccessLevel': 'Managed by the primary account holder',
      'family.dataIsolation': 'Isolation',
      'family.dataIsolationBody': 'Questionnaire answers, reports, medications, and diagnostics stay separate for each profile.',
      'family.switchToProfile': 'Switch to this profile',
      'family.invite': 'Send invite',
      'family.loadErrorTitle': 'Unable to load family profiles',
      'family.addMemberBody': 'Create a separate profile for each family member so records, appointments, and medications stay isolated.',
      'family.dateOfBirthOptional': 'Date of birth (optional)',
      'family.validationName': 'Enter the family member name before saving.',
      'family.createSuccess': 'Family member added successfully.',
      'family.createError': 'We could not add this family member. Review the details and try again.',
      'family.pendingMedicalAccess': 'Medical-record access will unlock after relationship evidence is verified.',
    },
    'ar': <String, String>{
      'common.continue': 'متابعة',
      'common.retry': 'إعادة المحاولة',
      'common.finishSetup': 'إنهاء الإعداد',
      'common.saving': 'جارٍ الحفظ…',
      'common.done': 'تم',
      'common.cancel': 'إلغاء',
      'common.back': 'رجوع',
      'common.requiredField': 'هذا الحقل مطلوب.',
      'language.badge': 'تجربة مريض جاهزة للسعودية',
      'language.subtitle': 'ابدأ رحلتك الصحية الرقمية بثقة ووضوح.',
      'language.chooseTitle': 'اختر لغتك',
      'language.chooseBody': 'حدد اللغة لتسجيل الدخول، والإعداد الأولي، ولوحة المريض.',
      'language.englishSubtitle': 'مناسب لمعظم المحتوى الحالي',
      'language.arabicSubtitle': 'واجهة عربية مهيأة للمريض',
      'language.note': 'بعد تسجيل الدخول ستكمل إعداد الملف الشخصي والموافقات مرة واحدة قبل استخدام الحجز والرعاية.',
      'signin.badge': 'تسجيل دخول المريض',
      'signin.title': 'مرحباً',
      'signin.subtitle': 'أدخل بياناتك واحصل على رمز لمرة واحدة للوصول إلى المواعيد والرسائل والوصفات والسجلات.',
      'signin.formTitle': 'تسجيل الدخول أو إنشاء حساب',
      'signin.formBody': 'يتم تسجيل المرضى الجدد تلقائياً. سنرسل رمزاً من ستة أرقام للتحقق من بريدك الإلكتروني.',
      'signin.firstNameLabel': 'الاسم الأول',
      'signin.lastNameLabel': 'اسم العائلة',
      'signin.identifierLabel': 'البريد الإلكتروني',
      'signin.seedTitle': 'حساب تجريبي',
      'signin.seedBody': 'يتم إرسال رمز التحقق عبر مسار الواجهة البرمجية الفعلي.',
      'signin.devPreview': 'معاينة رمز التطوير',
      'signin.submit': 'إرسال رمز التحقق',
      'signin.submitting': 'جارٍ الإرسال…',
      'otp.title': 'رمز المرور لمرة واحدة',
      'otp.subtitle': 'أدخل رمز التحقق المكون من ستة أرقام للمتابعة بأمان داخل CarePoint.',
      'otp.codeLabel': 'رمز التحقق',
      'otp.devCode': 'رمز التطوير',
      'otp.verify': 'تحقق وتابع',
      'otp.verifying': 'جارٍ التحقق…',
      'otp.resend': 'إعادة إرسال الرمز',
      'otp.enterFullCode': 'أدخل رمز التحقق الكامل المكون من 6 أرقام.',
      'otp.verifyCodeTitle': 'التحقق من الرمز',
      'otp.verifyCodeSubtitle': 'أرسلنا رمزاً مكوناً من ستة أرقام إلى {identifier}.',
      'otp.secureBadge': 'تسجيل دخول آمن',
      'otp.almostThere': 'أنت على وشك الانتهاء',
      'otp.heroBody': 'أدخل الرمز للمتابعة إلى تجربة CarePoint الخاصة بك.',
      'otp.timerWait': 'اطلب رمزاً آخر خلال 00:{seconds}',
      'otp.timerReady': 'يمكنك طلب رمز جديد الآن.',
      'otp.sending': 'جارٍ الإرسال…',
      'profile.title': 'إعداد الملف الشخصي',
      'profile.subtitle': 'بيانات الهوية والسلامة وتنسيق الرعاية',
      'profile.heroBadge': 'الخطوة 1 من 2',
      'profile.heroTitle': 'أكمل ملفك الشخصي',
      'profile.heroBody': 'نستخدم هذه البيانات لتخصيص الزيارات ومطابقة الخدمات ودعم الرعاية الآمنة.',
      'profile.fullName': 'الاسم الكامل',
      'profile.dateOfBirth': 'تاريخ الميلاد',
      'profile.gender': 'الجنس',
      'profile.genderFemale': 'أنثى',
      'profile.genderMale': 'ذكر',
      'profile.genderPreferNot': 'أفضل عدم الإفصاح',
      'profile.nationalId': 'الهوية الوطنية',
      'profile.emergencyContact': 'جهة اتصال للطوارئ',
      'profile.nationality': 'الجنسية',
      'profile.region': 'الدولة / المنطقة',
      'profile.regionSaudi': 'المملكة العربية السعودية',
      'profile.regionGcc': 'دول مجلس التعاون',
      'profile.regionOther': 'أخرى',
      'profile.requiredError': 'يرجى إكمال الحقول المطلوبة قبل المتابعة.',
      'consent.title': 'مركز الموافقات',
      'consent.hero': 'راجع تفضيلات التطبيب عن بعد ومشاركة البيانات والاتصالات قبل استخدام الخدمات الرقمية.',
      'consent.telehealthTitle': 'موافقة التطبيب عن بعد',
      'consent.telehealthBody': 'مطلوبة للزيارات المرئية واتصالات فريق الرعاية المرتبطة بالمواعيد.',
      'consent.dataTitle': 'موافقة مشاركة البيانات',
      'consent.dataBody': 'مطلوبة لمشاركة السجلات والتاريخ الصحي مع فريق الرعاية المعين داخل CarePoint.',
      'consent.notificationsTitle': 'الإشعارات',
      'consent.notificationsBody': 'تذكيرات اختيارية للمواعيد والرسائل وتحديثات الأدوية.',
      'consent.note': 'يتم الآن حفظ خيارات الموافقة عبر الواجهة البرمجية مع طوابع تدقيق وسجل زمني حتى يمكن استئناف الإعداد بأمان عبر الأجهزة.',
      'consent.requiredError': 'موافقة التطبيب عن بعد ومشاركة البيانات مطلوبة للمتابعة في هذا المسار الأولي.',
      'home.findProvider': 'ابحث عن مقدم خدمة',
      'home.viewAppointments': 'عرض المواعيد',
      'home.notifications': 'الإشعارات',
      'home.unread': 'غير مقروء',
      'home.highPriority': 'عالي الأولوية',
      'home.refills': 'إعادات الصرف',
      'home.active': 'نشط',
      'home.escalated': 'مصعّد',
      'home.governance': 'الحوكمة',
      'home.open': 'مفتوح',
      'home.highPriorityReminders': 'تذكيرات عالية الأولوية',
      'home.wallet': 'المحفظة',
      'home.methods': 'وسائل',
      'home.paymentsSavedMethods': 'المدفوعات والوسائل المحفوظة',
      'home.quickActions': 'إجراءات سريعة',
      'home.bookCare': 'احجز رعاية',
      'home.messages': 'الرسائل',
      'home.labs': 'التحاليل',
      'home.records': 'السجلات',
      'home.latestUpdates': 'آخر التحديثات',
      'home.noNotifications': 'لا توجد إشعارات جديدة',
      'home.caughtUp': 'أنت مطّلع على كل شيء حالياً.',
      'home.update': 'تحديث',
      'home.remindersAttention': 'تذكيرات تتطلب الانتباه',
      'home.reminder': 'تذكير',
      'home.schedulePending': 'الجدولة قيد الانتظار',
      'home.readyToBook': 'هل أنت مستعد لحجز زيارتك التالية؟',
      'home.readyToBookBody': 'ابحث عن مقدم خدمة، وقارن الخدمات، وأكمل الحجز في مسار موجه.',
      'home.welcomeBack': 'مرحباً بعودتك',

      'home.family': 'العائلة',
      'home.profile': 'الملف الشخصي',
      'home.activeProfile': 'الملف النشط',
      'entry.badge': 'دخول موحد للمريض',
      'entry.title': 'ابدأ من شاشة واحدة موجهة',
      'entry.subtitle': 'تم دمج المنطقة واللغة وتسجيل الدخول والموافقة قبل خطوة رمز التحقق.',
      'entry.heroBody': 'اختر اللغة، وحدد منطقة الرعاية، وأدخل البريد الإلكتروني أو الهاتف، ثم امنح الموافقات المطلوبة قبل خطوة رمز المرور لمرة واحدة.',
      'entry.languageTitle': 'اللغة والمنطقة',
      'entry.english': 'الإنجليزية',
      'entry.arabic': 'العربية',
      'entry.regionLabel': 'المنطقة',
      'entry.regionSaudi': 'المملكة العربية السعودية',
      'entry.regionGcc': 'دول مجلس التعاون',
      'entry.regionOther': 'أخرى',
      'entry.identifierLabel': 'البريد الإلكتروني أو رقم الجوال',
      'entry.identifierHint': 'name@example.com أو +9665…',
      'entry.consentTitle': 'موافقات الرعاية المطلوبة',
      'entry.consentBody': 'موافقة التطبيب عن بعد ومشاركة البيانات مطلوبة حتى يتمكن فريق الرعاية من التنسيق الآمن والوصول إلى سجلاتك عند حجز المواعيد.',
      'entry.continueToOtp': 'المتابعة إلى رمز التحقق',
      'entry.requiredError': 'أدخل المعرّف واقبل موافقة التطبيب عن بعد ومشاركة البيانات قبل المتابعة.',
      'profile.familyProfileTitle': 'ملف فرد من العائلة',
      'profile.familyProfileSubtitle': 'بيانات طبية منفصلة للشخص المحدد من أفراد العائلة',
      'profile.familyBadge': 'سياق تابع',
      'profile.familyHeroTitle': 'أدر هذا الملف العائلي بأمان',
      'profile.familyHeroBody': 'لكل فرد من العائلة إجابات استبيان منفصلة وتقارير مرفقة وضوابط مشاركة مستقلة.',
      'profile.questionnaireTitle': 'الاستبيان الصحي',
      'profile.questionnaireBody': 'سجل التاريخ الصحي والمخاطر والأدوية والبيانات الأساسية اللازمة للمراجعة السريرية الآمنة.',
      'profile.questionnaireProgress': 'تقدم الاستبيان',
      'profile.questionnaireVitalsTitle': 'الخطوة 1: القياسات الأساسية',
      'profile.questionnaireVitalsBody': 'أدخل القياسات الأساسية أولاً قبل متابعة بقية الاستبيان.',
      'profile.questionnaireHistoryTitle': 'الخطوة 2: التاريخ الطبي',
      'profile.questionnaireHistoryBody': 'أضف الحساسية والحالات المرضية والأدوية والعمليات الجراحية في قسم مبسط.',
      'profile.questionnaireSafetyTitle': 'الخطوة 3: نمط الحياة والسلامة',
      'profile.questionnaireSafetyBody': 'أكمل بيانات المخاطر الصحية وملاحظات الطوارئ قبل حفظ الملف.',
      'profile.questionnaireNext': 'القسم التالي',
      'profile.questionnaireReview': 'مراجعة القياسات',
      'profile.bloodType': 'فصيلة الدم',
      'profile.allergies': 'الحساسيات',
      'profile.conditions': 'الأمراض المزمنة',
      'profile.currentMedications': 'الأدوية الحالية',
      'profile.pastSurgeries': 'العمليات السابقة',
      'profile.heightCm': 'الطول (سم)',
      'profile.weightKg': 'الوزن (كجم)',
      'profile.heightValidationError': 'أدخل طولاً صحيحاً بالسنتيمتر أو اترك الحقل فارغاً.',
      'profile.weightValidationError': 'أدخل وزناً صحيحاً بالكيلوغرام أو اترك الحقل فارغاً.',
      'profile.questionnaireRecovered': 'تمت إعادة بعض اختيارات الاستبيان المحفوظة إلى قيم افتراضية آمنة لأنها غير مدعومة.',
      'profile.questionnaireLoadFallback': 'تعذر تحميل الاستبيان من الخادم. يمكنك متابعة التعديل ثم إعادة المحاولة.',
      'profile.questionnaireDedicatedSubtitle': 'أكمل الاستبيان في تدفق مستقل وموجّه بحيث يتم تحميل كل خطوة بشكل آمن وواضح.',
      'profile.questionnaireBadge': 'تدفق موجّه',
      'profile.questionnaireCompletionLabel': 'اكتمال الاستبيان',
      'profile.questionnaireOpen': 'فتح الاستبيان',
      'profile.questionnaireEdit': 'تعديل الاستبيان',
      'profile.questionnaireSaved': 'تم تحديث بيانات الاستبيان وهي جاهزة للحفظ مع الملف.',
      'profile.questionnaireDraftSaved': 'تم حفظ هذا القسم محلياً. تابع إلى الخطوة التالية.',
      'profile.questionnaireDraftRestored': 'تمت استعادة مسودة الاستبيان المحفوظة. تابع من حيث توقفت.',
      'profile.medicalDraftTitle': 'مسودة غير محفوظة للملف الطبي',
      'profile.medicalDraftBody': 'لديك تغييرات غير محفوظة في الاستبيان أو التقارير أو إعدادات المشاركة لهذا الملف. يمكنك استئنافها الآن أو حذف المسودة المحلية.',
      'profile.medicalDraftSaved': 'تم حفظ تغييرات الملف الطبي محلياً على هذا الجهاز.',
      'profile.medicalDraftRestored': 'تمت استعادة مسودة الملف الطبي غير المحفوظة على هذه الصفحة.',
      'profile.medicalDraftResumed': 'تم استئناف المسودة. راجع الاستبيان والتقارير قبل الحفظ.',
      'profile.medicalDraftDiscarded': 'تم حذف مسودة الملف الطبي المحلية وإعادة تحميل آخر بيانات محفوظة.',
      'profile.medicalDraftResume': 'استئناف المسودة',
      'profile.medicalDraftDiscard': 'حذف المسودة',
      'profile.questionnaireCompleteAndReturn': 'إكمال والعودة',
      'profile.questionnaireSummaryBody': 'افتح صفحة الاستبيان المستقلة لإكمال أو مراجعة الأسئلة الصحية الموجّهة.',
      'profile.questionnaireEmptyStateTitle': 'لم يبدأ الاستبيان بعد',
      'profile.questionnaireEmptyStateBody': 'افتح الاستبيان لتسجيل القياسات الأساسية والتاريخ الطبي وبيانات السلامة قبل حفظ الملف.',
      'profile.questionnaireCompleted': 'الاستبيان مكتمل',
      'profile.questionnaireIncomplete': 'الاستبيان غير مكتمل',
      'profile.questionnaireVitalsRequired': 'يجب إدخال الطول والوزن قبل الانتقال إلى الخطوة التالية من الاستبيان.',
      'profile.smokingNever': 'لا أدخن',
      'profile.smokingFormer': 'مدخن سابق',
      'profile.smokingCurrent': 'مدخن حالياً',
      'profile.pregnancyNotApplicable': 'غير منطبق',
      'profile.pregnancyPregnant': 'حامل',
      'profile.pregnancyPlanning': 'أخطط للحمل',
      'profile.preferNotToSay': 'أفضل عدم الإجابة',
      'profile.smokingStatus': 'حالة التدخين',
      'profile.pregnancyStatus': 'حالة الحمل',
      'profile.emergencyNotes': 'ملاحظات الطوارئ',
      'profile.reportsTitle': 'التاريخ التشخيصي والتقارير',
      'profile.reportsBody': 'أرفق بيانات التقارير وتحكم في الأطباء المجدولين الذين يمكنهم مراجعتها.',
      'profile.addReport': 'إضافة تقرير',
      'profile.reportFileName': 'اسم ملف التقرير',
      'profile.reportCategory': 'الفئة',
      'profile.reportDate': 'تاريخ التقرير',
      'profile.providerName': 'اسم الطبيب / المُعد',
      'profile.facilityName': 'المنشأة',
      'profile.notes': 'ملاحظات',
      'profile.shareWithDoctors': 'المشاركة مع الأطباء المجدولين فقط',
      'profile.shareWithDoctorsBody': 'تبقى التقارير خاصة ما لم يمنح المريض إذناً صريحاً للأطباء المرتبطين بمواعيد مجدولة.',
      'profile.sharedDoctorList': 'الأطباء المجدولون حالياً',
      'profile.noReportsTitle': 'لا توجد تقارير مرفقة بعد',
      'profile.noReportsBody': 'أضف التاريخ التشخيصي أو نتائج التصوير أو ملخصات الخروج أو تقارير المختبر هنا.',
      'profile.endOfPageTitle': 'لا توجد معلومات إضافية',
      'profile.endOfPageBody': 'لقد وصلت إلى نهاية صفحة الملف الشخصي. اسحب للأسفل للتحديث إذا كنت تتوقع تفاصيل إضافية.',
      'family.title': 'ملفات العائلة',
      'family.subtitle': 'أضف التابعين وبدّل بين الملفات مع إبقاء البيانات الطبية معزولة لكل مريض.',
      'family.profileCount': 'ملفات',
      'family.heroTitle': 'إدارة الرعاية لكل أفراد العائلة',
      'family.heroBody': 'أنشئ ملفات منفصلة لأفراد العائلة وبدّل بينها وأكمل البيانات الطبية لكل شخص بشكل مستقل.',
      'family.addMember': 'إضافة فرد من العائلة',
      'family.memberName': 'اسم فرد العائلة',
      'family.relationship': 'صلة القرابة',
      'family.currentContext': 'سياق المريض الحالي',
      'family.selfProfile': 'ملفي',
      'family.switchToSelf': 'العودة إلى ملفي',
      'family.defaultAccessLevel': 'تدار بواسطة صاحب الحساب الرئيسي',
      'family.dataIsolation': 'العزل',
      'family.dataIsolationBody': 'تبقى إجابات الاستبيان والتقارير والأدوية والتشخيصات منفصلة لكل ملف.',
      'family.switchToProfile': 'التبديل إلى هذا الملف',
      'family.invite': 'إرسال دعوة',
      'family.loadErrorTitle': 'تعذر تحميل ملفات العائلة',
      'family.addMemberBody': 'أنشئ ملفاً منفصلاً لكل فرد من العائلة حتى تبقى السجلات والمواعيد والأدوية معزولة.',
      'family.dateOfBirthOptional': 'تاريخ الميلاد (اختياري)',
      'family.validationName': 'أدخل اسم فرد العائلة قبل الحفظ.',
      'family.createSuccess': 'تمت إضافة فرد العائلة بنجاح.',
      'family.createError': 'تعذر إضافة فرد العائلة. راجع البيانات ثم أعد المحاولة.',
      'family.pendingMedicalAccess': 'سيتم تفعيل الوصول إلى السجلات الطبية بعد التحقق من مستندات صلة القرابة.',
    },
  };

  String t(String key, {Map<String, String> params = const <String, String>{}}) {
    final String languageCode = _values.containsKey(locale.languageCode) ? locale.languageCode : 'en';
    String value = _values[languageCode]?[key] ?? _values['en']?[key] ?? key;
    params.forEach((String paramKey, String paramValue) {
      value = value.replaceAll('{$paramKey}', paramValue);
    });
    return value;
  }
}

class _AppLocalizationsDelegate extends LocalizationsDelegate<AppLocalizations> {
  const _AppLocalizationsDelegate();

  @override
  bool isSupported(Locale locale) => <String>['en', 'ar'].contains(locale.languageCode);

  @override
  Future<AppLocalizations> load(Locale locale) async => AppLocalizations(locale);

  @override
  bool shouldReload(covariant LocalizationsDelegate<AppLocalizations> old) => false;
}

extension AppLocalizationsBuildContext on BuildContext {
  AppLocalizations get l10n => AppLocalizations.of(this);
}
