from __future__ import annotations

from dataclasses import dataclass
import hashlib

from ..models import JobAccepted, JobEnvelope, JobResult, JobStatus, JobType


@dataclass(frozen=True)
class JobRoute:
    routed_to: str
    celery_task_name: str


JOB_ROUTES: dict[JobType, JobRoute] = {
    JobType.ADMIN_AUDIT_EXPORT: JobRoute("python.admin.audit_export.v14", "carepoint.jobs.handle"),
    JobType.ADMIN_ACCOUNTS_BULK_VALIDATE: JobRoute("python.admin.accounts_bulk_validate.v14", "carepoint.jobs.handle"),
    JobType.ADMIN_ACCOUNTS_READ_MODEL: JobRoute("python.admin.accounts_read_model.v14", "carepoint.jobs.handle"),
    JobType.ADMIN_PROVIDER_ROLE_RECONCILE: JobRoute("python.admin.provider_role_reconcile.v14", "carepoint.jobs.handle"),
    JobType.SCHEDULING_AVAILABILITY_SNAPSHOT: JobRoute("python.scheduling.availability_snapshot.v14", "carepoint.jobs.handle"),
    JobType.MESSAGING_REMINDER_PLAN: JobRoute("python.messaging.reminder_plan.v14", "carepoint.jobs.handle"),
    JobType.BILLING_PAYMENT_RECONCILE: JobRoute("python.billing.payment_reconcile.v14", "carepoint.jobs.handle"),
    JobType.CLINICAL_RECORDS_ACCESS_AUDIT: JobRoute("python.clinical.records_access_audit.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_DB_INDEX_ADVISORY: JobRoute("python.platform.db_index_advisory.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_SLO_REGRESSION_REPORT: JobRoute("python.platform.slo_regression_report.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_CONTRACT_REPLAY: JobRoute("python.platform.contract_replay.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_PRIVACY_PREFLIGHT: JobRoute("python.platform.privacy_preflight.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_RELEASE_DECISION: JobRoute("python.platform.release_decision.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_ROLLBACK_DRILL: JobRoute("python.platform.rollback_drill.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_POST_DEPLOY_VERIFY: JobRoute("python.platform.post_deploy_verify.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_CHANGE_TICKET_BUNDLE: JobRoute("python.platform.change_ticket_bundle.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_OPERATIONAL_HANDOFF: JobRoute("python.platform.operational_handoff.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_INCIDENT_SIMULATION: JobRoute("python.platform.incident_simulation.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_CAPACITY_PLAN: JobRoute("python.platform.capacity_plan.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_ALERT_POLICY_REVIEW: JobRoute("python.platform.alert_policy_review.v14", "carepoint.jobs.handle"),
    JobType.PLATFORM_DEPENDENCY_READINESS: JobRoute("python.platform.dependency_readiness.v15", "carepoint.jobs.handle"),
    JobType.PLATFORM_PRODUCTION_READINESS: JobRoute("python.platform.production_readiness.v15", "carepoint.jobs.handle"),
    JobType.PLATFORM_DATA_RETENTION_REVIEW: JobRoute("python.platform.data_retention_review.v16", "carepoint.jobs.handle"),
    JobType.PLATFORM_AUDIT_TRAIL_REVIEW: JobRoute("python.platform.audit_trail_review.v16", "carepoint.jobs.handle"),
    JobType.PLATFORM_SECURITY_POSTURE_REVIEW: JobRoute("python.platform.security_posture_review.v17", "carepoint.jobs.handle"),
    JobType.PLATFORM_SUPPLY_CHAIN_REVIEW: JobRoute("python.platform.supply_chain_review.v17", "carepoint.jobs.handle"),
    JobType.PLATFORM_SCHEMA_MIGRATION_REHEARSAL: JobRoute("python.platform.schema_migration_rehearsal.v18", "carepoint.jobs.handle"),
    JobType.PLATFORM_BACKUP_RESTORE_DRILL: JobRoute("python.platform.backup_restore_drill.v18", "carepoint.jobs.handle"),
    JobType.PLATFORM_OBSERVABILITY_COVERAGE_REVIEW: JobRoute("python.platform.observability_coverage_review.v19", "carepoint.jobs.handle"),
    JobType.PLATFORM_FEATURE_FLAG_REVIEW: JobRoute("python.platform.feature_flag_review.v19", "carepoint.jobs.handle"),
    JobType.PLATFORM_DOMAIN_MIGRATION_READINESS: JobRoute("python.platform.domain_migration_readiness.v20", "carepoint.jobs.handle"),
    JobType.PLATFORM_CUTOVER_PLAN: JobRoute("python.platform.cutover_plan.v20", "carepoint.jobs.handle"),
    JobType.PLATFORM_OWNER_REGISTRY_REVIEW: JobRoute("python.platform.owner_registry_review.v21", "carepoint.jobs.handle"),
    JobType.PLATFORM_POST_CUTOVER_MONITOR: JobRoute("python.platform.post_cutover_monitor.v21", "carepoint.jobs.handle"),
    JobType.PLATFORM_LEGACY_PATH_DECOMMISSION: JobRoute("python.platform.legacy_path_decommission.v22", "carepoint.jobs.handle"),
    JobType.PLATFORM_STEADY_STATE_OPERATIONS_REVIEW: JobRoute("python.platform.steady_state_operations_review.v22", "carepoint.jobs.handle"),
    JobType.PLATFORM_QUEUE_RESILIENCE_REVIEW: JobRoute("python.platform.queue_resilience_review.v23", "carepoint.jobs.handle"),
    JobType.PLATFORM_ARTIFACT_INTEGRITY_REVIEW: JobRoute("python.platform.artifact_integrity_review.v23", "carepoint.jobs.handle"),
    JobType.PLATFORM_RUNBOOK_FRESHNESS_REVIEW: JobRoute("python.platform.runbook_freshness_review.v24", "carepoint.jobs.handle"),
    JobType.PLATFORM_SUPPORT_ESCALATION_REVIEW: JobRoute("python.platform.support_escalation_review.v24", "carepoint.jobs.handle"),
    JobType.PLATFORM_COST_GUARDRAIL_REVIEW: JobRoute("python.platform.cost_guardrail_review.v25", "carepoint.jobs.handle"),
    JobType.PLATFORM_ENVIRONMENT_PARITY_REVIEW: JobRoute("python.platform.environment_parity_review.v25", "carepoint.jobs.handle"),
    JobType.PLATFORM_ACCESS_CONTROL_REVIEW: JobRoute("python.platform.access_control_review.v26", "carepoint.jobs.handle"),
    JobType.PLATFORM_DATA_QUALITY_REVIEW: JobRoute("python.platform.data_quality_review.v26", "carepoint.jobs.handle"),
    JobType.PLATFORM_CI_STAGING_VALIDATION_REVIEW: JobRoute("python.platform.ci_staging_validation_review.v27", "carepoint.jobs.handle"),
    JobType.PLATFORM_RELEASE_CLOSURE_REVIEW: JobRoute("python.platform.release_closure_review.v27", "carepoint.jobs.handle"),
    JobType.PLATFORM_PRODUCTION_CANARY_OBSERVATION_REVIEW: JobRoute("python.platform.production_canary_observation_review.v28", "carepoint.jobs.handle"),
    JobType.PLATFORM_INCIDENT_RESPONSE_READINESS_REVIEW: JobRoute("python.platform.incident_response_readiness_review.v28", "carepoint.jobs.handle"),
    JobType.PLATFORM_TRAFFIC_PROMOTION_READINESS_REVIEW: JobRoute("python.platform.traffic_promotion_readiness_review.v29", "carepoint.jobs.handle"),
    JobType.PLATFORM_EVIDENCE_RETENTION_AUDIT_REVIEW: JobRoute("python.platform.evidence_retention_audit_review.v29", "carepoint.jobs.handle"),
    JobType.PLATFORM_SLO_ERROR_BUDGET_REVIEW: JobRoute("python.platform.slo_error_budget_review.v30", "carepoint.jobs.handle"),
    JobType.PLATFORM_AUTO_ROLLBACK_SAFEGUARD_REVIEW: JobRoute("python.platform.auto_rollback_safeguard_review.v30", "carepoint.jobs.handle"),
    JobType.PLATFORM_THIRD_PARTY_DEPENDENCY_REVIEW: JobRoute("python.platform.third_party_dependency_review.v31", "carepoint.jobs.handle"),
    JobType.PLATFORM_CAPACITY_SCALING_READINESS_REVIEW: JobRoute("python.platform.capacity_scaling_readiness_review.v31", "carepoint.jobs.handle"),
    JobType.PLATFORM_COMPLIANCE_PRIVACY_EVIDENCE_REVIEW: JobRoute("python.platform.compliance_privacy_evidence_review.v32", "carepoint.jobs.handle"),
    JobType.PLATFORM_RUNBOOK_DRILL_VERIFICATION_REVIEW: JobRoute("python.platform.runbook_drill_verification_review.v32", "carepoint.jobs.handle"),
    JobType.PLATFORM_DISASTER_RECOVERY_BACKUP_REVIEW: JobRoute("python.platform.disaster_recovery_backup_review.v33", "carepoint.jobs.handle"),
    JobType.PLATFORM_CHANGE_MIGRATION_READINESS_REVIEW: JobRoute("python.platform.change_migration_readiness_review.v33", "carepoint.jobs.handle"),
    JobType.PLATFORM_CONFIGURATION_SECRET_ROTATION_REVIEW: JobRoute("python.platform.configuration_secret_rotation_review.v34", "carepoint.jobs.handle"),
    JobType.PLATFORM_MAINTENANCE_WINDOW_READINESS_REVIEW: JobRoute("python.platform.maintenance_window_readiness_review.v34", "carepoint.jobs.handle"),
    JobType.PLATFORM_AUDIT_FORENSICS_READINESS_REVIEW: JobRoute("python.platform.audit_forensics_readiness_review.v35", "carepoint.jobs.handle"),
    JobType.PLATFORM_BUSINESS_CONTINUITY_READINESS_REVIEW: JobRoute("python.platform.business_continuity_readiness_review.v35", "carepoint.jobs.handle"),
    JobType.PLATFORM_POST_INCIDENT_LEARNING_REVIEW: JobRoute("python.platform.post_incident_learning_review.v36", "carepoint.jobs.handle"),
    JobType.PLATFORM_TECH_DEBT_GOVERNANCE_REVIEW: JobRoute("python.platform.tech_debt_governance_review.v36", "carepoint.jobs.handle"),
    JobType.PLATFORM_VENDOR_RESILIENCE_REVIEW: JobRoute("python.platform.vendor_resilience_review.v37", "carepoint.jobs.handle"),
    JobType.PLATFORM_KNOWLEDGE_TRANSFER_READINESS_REVIEW: JobRoute("python.platform.knowledge_transfer_readiness_review.v37", "carepoint.jobs.handle"),
    JobType.PLATFORM_ARCHITECTURE_OWNERSHIP_REVIEW: JobRoute("python.platform.architecture_ownership_review.v38", "carepoint.jobs.handle"),
    JobType.PLATFORM_EXECUTIVE_METRICS_GOVERNANCE_REVIEW: JobRoute("python.platform.executive_metrics_governance_review.v38", "carepoint.jobs.handle"),
    JobType.PLATFORM_DOMAIN_ADOPTION_READINESS_REVIEW: JobRoute("python.platform.domain_adoption_readiness_review.v39", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_TWO_ROLLOUT_GOVERNANCE_REVIEW: JobRoute("python.platform.phase_two_rollout_governance_review.v39", "carepoint.jobs.handle"),
    JobType.PLATFORM_DOMAIN_PILOT_EXECUTION_REVIEW: JobRoute("python.platform.domain_pilot_execution_review.v40", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_TWO_EXPANSION_CONTROL_REVIEW: JobRoute("python.platform.phase_two_expansion_control_review.v40", "carepoint.jobs.handle"),
    JobType.PLATFORM_DOMAIN_OUTCOME_MEASUREMENT_REVIEW: JobRoute("python.platform.domain_outcome_measurement_review.v41", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_TWO_FEEDBACK_ADOPTION_REVIEW: JobRoute("python.platform.phase_two_feedback_adoption_review.v41", "carepoint.jobs.handle"),
    JobType.PLATFORM_DOMAIN_GRADUATION_READINESS_REVIEW: JobRoute("python.platform.domain_graduation_readiness_review.v43", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_TWO_LEARNING_CONSOLIDATION_REVIEW: JobRoute("python.platform.phase_two_learning_consolidation_review.v43", "carepoint.jobs.handle"),
    JobType.PLATFORM_DOMAIN_WIDE_ADOPTION_READINESS_REVIEW: JobRoute("python.platform.domain_wide_adoption_readiness_review.v43", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_TWO_SUPPORT_TRANSITION_REVIEW: JobRoute("python.platform.phase_two_support_transition_review.v43", "carepoint.jobs.handle"),
    JobType.PLATFORM_DOMAIN_ADOPTION_STABILIZATION_REVIEW: JobRoute("python.platform.domain_adoption_stabilization_review.v44", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_TWO_VALUE_REALIZATION_REVIEW: JobRoute("python.platform.phase_two_value_realization_review.v44", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_TWO_CLOSURE_ACCEPTANCE_REVIEW: JobRoute("python.platform.phase_two_closure_acceptance_review.v45", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_THREE_TRANSITION_READINESS_REVIEW: JobRoute("python.platform.phase_three_transition_readiness_review.v45", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_THREE_DOMAIN_WAVE_READINESS_REVIEW: JobRoute("python.platform.phase_three_domain_wave_readiness_review.v46", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_THREE_OPERATING_MODEL_ALIGNMENT_REVIEW: JobRoute("python.platform.phase_three_operating_model_alignment_review.v46", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_THREE_WAVE_EXECUTION_REVIEW: JobRoute("python.platform.phase_three_wave_execution_review.v47", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_THREE_ADOPTION_VALUE_TRACKING_REVIEW: JobRoute("python.platform.phase_three_adoption_value_tracking_review.v47", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_THREE_GAP_REMEDIATION_REVIEW: JobRoute("python.platform.phase_three_gap_remediation_review.v48", "carepoint.jobs.handle"),
    JobType.PLATFORM_MIGRATION_STAGE_COMPLETION_READINESS_REVIEW: JobRoute("python.platform.migration_stage_completion_readiness_review.v48", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_THREE_REMEDIATION_CLOSURE_REVIEW: JobRoute("python.platform.phase_three_remediation_closure_review.v49", "carepoint.jobs.handle"),
    JobType.PLATFORM_EXECUTIVE_OPERATIONAL_HANDOFF_REVIEW: JobRoute("python.platform.executive_operational_handoff_review.v49", "carepoint.jobs.handle"),
    JobType.PLATFORM_GLOBAL_TASK_STATUS_TRACKING_REVIEW: JobRoute("python.platform.global_task_status_tracking_review.v52", "carepoint.jobs.handle"),
    JobType.PLATFORM_PROJECT_STATE_HEALTH_REVIEW: JobRoute("python.platform.project_state_health_review.v52", "carepoint.jobs.handle"),
    JobType.PLATFORM_FINAL_ACCEPTANCE_EVIDENCE_REVIEW: JobRoute("python.platform.final_acceptance_evidence_review.v53", "carepoint.jobs.handle"),
    JobType.PLATFORM_STAGE_EXIT_READINESS_REVIEW: JobRoute("python.platform.stage_exit_readiness_review.v53", "carepoint.jobs.handle"),
    JobType.PLATFORM_STAGE_CLOSURE_CERTIFICATION_REVIEW: JobRoute("python.platform.stage_closure_certification_review.v54", "carepoint.jobs.handle"),
    JobType.PLATFORM_POST_CLOSURE_OPERATIONAL_TRANSITION_REVIEW: JobRoute("python.platform.post_closure_operational_transition_review.v54", "carepoint.jobs.handle"),
    JobType.PLATFORM_POST_CLOSURE_MONITORING_REVIEW: JobRoute("python.platform.post_closure_monitoring_review.v55", "carepoint.jobs.handle"),
    JobType.PLATFORM_STEADY_STATE_TRANSFER_VALIDATION_REVIEW: JobRoute("python.platform.steady_state_transfer_validation_review.v55", "carepoint.jobs.handle"),
    JobType.PLATFORM_STEADY_STATE_OPERATIONAL_ASSURANCE_REVIEW: JobRoute("python.platform.steady_state_operational_assurance_review.v56", "carepoint.jobs.handle"),
    JobType.PLATFORM_CONTINUOUS_IMPROVEMENT_BACKLOG_REVIEW: JobRoute("python.platform.continuous_improvement_backlog_review.v56", "carepoint.jobs.handle"),
    JobType.PLATFORM_STABLE_OPERATIONS_OPTIMIZATION_REVIEW: JobRoute("python.platform.stable_operations_optimization_review.v57", "carepoint.jobs.handle"),
    JobType.PLATFORM_RECURRING_MAINTENANCE_CYCLE_READINESS_REVIEW: JobRoute("python.platform.recurring_maintenance_cycle_readiness_review.v57", "carepoint.jobs.handle"),
    JobType.PLATFORM_MAINTENANCE_CYCLE_EXECUTION_REVIEW: JobRoute("python.platform.maintenance_cycle_execution_review.v58", "carepoint.jobs.handle"),
    JobType.PLATFORM_LONG_TERM_OPERABILITY_SUSTAINABILITY_REVIEW: JobRoute("python.platform.long_term_operability_sustainability_review.v58", "carepoint.jobs.handle"),
    JobType.PLATFORM_RECURRING_OPERATIONAL_MATURITY_AUDIT_REVIEW: JobRoute("python.platform.recurring_operational_maturity_audit_review.v59", "carepoint.jobs.handle"),
    JobType.PLATFORM_STABLE_STATE_CONTINUITY_CONTROL_REVIEW: JobRoute("python.platform.stable_state_continuity_control_review.v59", "carepoint.jobs.handle"),
    JobType.PLATFORM_OPERATIONAL_RESILIENCE_GOVERNANCE_REVIEW: JobRoute("python.platform.operational_resilience_governance_review.v60", "carepoint.jobs.handle"),
    JobType.PLATFORM_RECOVERY_CAPABILITY_VALIDATION_REVIEW: JobRoute("python.platform.recovery_capability_validation_review.v60", "carepoint.jobs.handle"),
    JobType.PLATFORM_OPERATIONAL_RESILIENCE_OPTIMIZATION_REVIEW: JobRoute("python.platform.operational_resilience_optimization_review.v61", "carepoint.jobs.handle"),
    JobType.PLATFORM_AUTOMATED_CONTINUITY_PREPAREDNESS_REVIEW: JobRoute("python.platform.automated_continuity_preparedness_review.v61", "carepoint.jobs.handle"),
    JobType.PLATFORM_AUTOMATED_CONTINUITY_EXECUTION_VALIDATION_REVIEW: JobRoute("python.platform.automated_continuity_execution_validation_review.v62", "carepoint.jobs.handle"),
    JobType.PLATFORM_OPERATIONAL_RESILIENCE_FEEDBACK_LOOP_REVIEW: JobRoute("python.platform.operational_resilience_feedback_loop_review.v62", "carepoint.jobs.handle"),
    JobType.PLATFORM_FINAL_CLOSURE_EVIDENCE_PACKAGE_REVIEW: JobRoute("python.platform.final_closure_evidence_package_review.v63", "carepoint.jobs.handle"),
    JobType.PLATFORM_GLOBAL_IMPLEMENTATION_COMPLETION_CHECKLIST_REVIEW: JobRoute("python.platform.global_implementation_completion_checklist_review.v63", "carepoint.jobs.handle"),
    JobType.PLATFORM_FINAL_OPERATIONAL_HANDOVER_REVIEW: JobRoute("python.platform.final_operational_handover_review.v64", "carepoint.jobs.handle"),
    JobType.PLATFORM_PHASE_CLOSURE_CERTIFICATION_REVIEW: JobRoute("python.platform.phase_closure_certification_review.v64", "carepoint.jobs.handle"),
    JobType.NOTIFICATIONS_DISPATCH: JobRoute("python.notifications.dispatch.v14", "carepoint.jobs.handle"),
    JobType.ANALYTICS_SNAPSHOT: JobRoute("python.analytics.snapshot.v14", "carepoint.jobs.handle"),
    JobType.AI_TRIAGE_PREVIEW: JobRoute("python.ai.triage_preview.v14", "carepoint.jobs.handle"),
}


def build_job_id(idempotency_key: str) -> str:
    return "job_" + hashlib.sha256(idempotency_key.encode("utf-8")).hexdigest()[:24]


def build_acceptance(
    job: JobEnvelope,
    *,
    queued: bool,
    task_id: str | None = None,
    status: JobStatus = JobStatus.ACCEPTED,
    duplicate: bool = False,
    result: JobResult | None = None,
) -> JobAccepted:
    route = JOB_ROUTES[job.job_type]
    return JobAccepted(
        accepted=True,
        jobId=build_job_id(job.idempotency_key),
        jobType=job.job_type,
        idempotencyKey=job.idempotency_key,
        correlationId=job.correlation_id,
        routedTo=route.routed_to,
        queued=queued,
        taskId=task_id,
        dryRun=job.dry_run,
        status=status,
        duplicate=duplicate,
        result=result,
    )
